global:
  scrape_interval:     2s # By default, scrape targets every 15 seconds.
  evaluation_interval: 2s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    cluster: 'test-cluster'
    monitor: "prometheus"


scrape_configs:
  - job_name: "node_exporter"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.1.102:9600'

  - job_name: "CPO"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.1.102:5632'

  - job_name: "K2Node"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.1.102:5635'

  - job_name: "persistence"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.1.102:5636'

  - job_name: "TSO"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.1.102:5639'

